language: node_js  #设置语言

cache:
  apt: true
  directories:
    - node_modules

node_js: 13.2.0  #设置相应的版本

install:
  - npm install  #安装hexo及插件

script:
  - hexo cl  #清除
  - hexo g  #生成

after_script:
  - cp ./README.md ./public
  - cd ./public
  - git init
  - git config user.name "LeoEatle"  #修改name
  - git config user.email "liuyitao811@hotmail.com"  #修改email
  - git add .
  - git commit -m "update hexo blog"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称

branches:
  only:
    - master  #只监测master
env:
 global:
   - GH_REF: github.com/LeoEatle/leoeatle.github.io.git  #设置GH_REF